// Generated by gencpp from file xihelm_pkg/Navigate2DFeedback.msg
// DO NOT EDIT!


#ifndef XIHELM_PKG_MESSAGE_NAVIGATE2DFEEDBACK_H
#define XIHELM_PKG_MESSAGE_NAVIGATE2DFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xihelm_pkg
{
template <class ContainerAllocator>
struct Navigate2DFeedback_
{
  typedef Navigate2DFeedback_<ContainerAllocator> Type;

  Navigate2DFeedback_()
    : distance_remaining(0.0)  {
    }
  Navigate2DFeedback_(const ContainerAllocator& _alloc)
    : distance_remaining(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_remaining_type;
  _distance_remaining_type distance_remaining;





  typedef boost::shared_ptr< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct Navigate2DFeedback_

typedef ::xihelm_pkg::Navigate2DFeedback_<std::allocator<void> > Navigate2DFeedback;

typedef boost::shared_ptr< ::xihelm_pkg::Navigate2DFeedback > Navigate2DFeedbackPtr;
typedef boost::shared_ptr< ::xihelm_pkg::Navigate2DFeedback const> Navigate2DFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator1> & lhs, const ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.distance_remaining == rhs.distance_remaining;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator1> & lhs, const ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xihelm_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64b64afc81806ad83ed607add12142ca";
  }

  static const char* value(const ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64b64afc81806ad8ULL;
  static const uint64_t static_value2 = 0x3ed607add12142caULL;
};

template<class ContainerAllocator>
struct DataType< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xihelm_pkg/Navigate2DFeedback";
  }

  static const char* value(const ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float32 distance_remaining\n"
"\n"
;
  }

  static const char* value(const ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_remaining);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Navigate2DFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xihelm_pkg::Navigate2DFeedback_<ContainerAllocator>& v)
  {
    s << indent << "distance_remaining: ";
    Printer<float>::stream(s, indent + "  ", v.distance_remaining);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XIHELM_PKG_MESSAGE_NAVIGATE2DFEEDBACK_H
