// Generated by gencpp from file xihelm_pkg/OddEvenCheck.msg
// DO NOT EDIT!


#ifndef XIHELM_PKG_MESSAGE_ODDEVENCHECK_H
#define XIHELM_PKG_MESSAGE_ODDEVENCHECK_H

#include <ros/service_traits.h>


#include <xihelm_pkg/OddEvenCheckRequest.h>
#include <xihelm_pkg/OddEvenCheckResponse.h>


namespace xihelm_pkg
{

struct OddEvenCheck
{

typedef OddEvenCheckRequest Request;
typedef OddEvenCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OddEvenCheck
} // namespace xihelm_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xihelm_pkg::OddEvenCheck > {
  static const char* value()
  {
    return "4ff0b0ab1ed04611e3a2b4090af9ee4f";
  }

  static const char* value(const ::xihelm_pkg::OddEvenCheck&) { return value(); }
};

template<>
struct DataType< ::xihelm_pkg::OddEvenCheck > {
  static const char* value()
  {
    return "xihelm_pkg/OddEvenCheck";
  }

  static const char* value(const ::xihelm_pkg::OddEvenCheck&) { return value(); }
};


// service_traits::MD5Sum< ::xihelm_pkg::OddEvenCheckRequest> should match
// service_traits::MD5Sum< ::xihelm_pkg::OddEvenCheck >
template<>
struct MD5Sum< ::xihelm_pkg::OddEvenCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xihelm_pkg::OddEvenCheck >::value();
  }
  static const char* value(const ::xihelm_pkg::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xihelm_pkg::OddEvenCheckRequest> should match
// service_traits::DataType< ::xihelm_pkg::OddEvenCheck >
template<>
struct DataType< ::xihelm_pkg::OddEvenCheckRequest>
{
  static const char* value()
  {
    return DataType< ::xihelm_pkg::OddEvenCheck >::value();
  }
  static const char* value(const ::xihelm_pkg::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xihelm_pkg::OddEvenCheckResponse> should match
// service_traits::MD5Sum< ::xihelm_pkg::OddEvenCheck >
template<>
struct MD5Sum< ::xihelm_pkg::OddEvenCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xihelm_pkg::OddEvenCheck >::value();
  }
  static const char* value(const ::xihelm_pkg::OddEvenCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xihelm_pkg::OddEvenCheckResponse> should match
// service_traits::DataType< ::xihelm_pkg::OddEvenCheck >
template<>
struct DataType< ::xihelm_pkg::OddEvenCheckResponse>
{
  static const char* value()
  {
    return DataType< ::xihelm_pkg::OddEvenCheck >::value();
  }
  static const char* value(const ::xihelm_pkg::OddEvenCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XIHELM_PKG_MESSAGE_ODDEVENCHECK_H
