// Generated by gencpp from file xihelm_pkg/SurveyCamera.msg
// DO NOT EDIT!


#ifndef XIHELM_PKG_MESSAGE_SURVEYCAMERA_H
#define XIHELM_PKG_MESSAGE_SURVEYCAMERA_H

#include <ros/service_traits.h>


#include <xihelm_pkg/SurveyCameraRequest.h>
#include <xihelm_pkg/SurveyCameraResponse.h>


namespace xihelm_pkg
{

struct SurveyCamera
{

typedef SurveyCameraRequest Request;
typedef SurveyCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SurveyCamera
} // namespace xihelm_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xihelm_pkg::SurveyCamera > {
  static const char* value()
  {
    return "be9d1066f5c2d761478f03b60acd3f19";
  }

  static const char* value(const ::xihelm_pkg::SurveyCamera&) { return value(); }
};

template<>
struct DataType< ::xihelm_pkg::SurveyCamera > {
  static const char* value()
  {
    return "xihelm_pkg/SurveyCamera";
  }

  static const char* value(const ::xihelm_pkg::SurveyCamera&) { return value(); }
};


// service_traits::MD5Sum< ::xihelm_pkg::SurveyCameraRequest> should match
// service_traits::MD5Sum< ::xihelm_pkg::SurveyCamera >
template<>
struct MD5Sum< ::xihelm_pkg::SurveyCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xihelm_pkg::SurveyCamera >::value();
  }
  static const char* value(const ::xihelm_pkg::SurveyCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xihelm_pkg::SurveyCameraRequest> should match
// service_traits::DataType< ::xihelm_pkg::SurveyCamera >
template<>
struct DataType< ::xihelm_pkg::SurveyCameraRequest>
{
  static const char* value()
  {
    return DataType< ::xihelm_pkg::SurveyCamera >::value();
  }
  static const char* value(const ::xihelm_pkg::SurveyCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xihelm_pkg::SurveyCameraResponse> should match
// service_traits::MD5Sum< ::xihelm_pkg::SurveyCamera >
template<>
struct MD5Sum< ::xihelm_pkg::SurveyCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xihelm_pkg::SurveyCamera >::value();
  }
  static const char* value(const ::xihelm_pkg::SurveyCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xihelm_pkg::SurveyCameraResponse> should match
// service_traits::DataType< ::xihelm_pkg::SurveyCamera >
template<>
struct DataType< ::xihelm_pkg::SurveyCameraResponse>
{
  static const char* value()
  {
    return DataType< ::xihelm_pkg::SurveyCamera >::value();
  }
  static const char* value(const ::xihelm_pkg::SurveyCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XIHELM_PKG_MESSAGE_SURVEYCAMERA_H
